/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_applejuicenet_nativeclasses_JNISubNetMask */

#ifndef _Included_de_applejuicenet_nativeclasses_JNISubNetMask
#define _Included_de_applejuicenet_nativeclasses_JNISubNetMask
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_applejuicenet_nativeclasses_JNISubNetMask
 * Method:    getSubNetMask
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_de_applejuicenet_nativeclasses_JNISubNetMask_getSubNetMask
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
